### ISSUE TITLE
Cannot upgrade in SSH

### ISSUE THREAD

**Issue by tulipo** [jaedb/Iris#153]
Can't upgrade Iris via command line. Typing     sudo pip install --upgrade Mopidy-Iris    i get:

Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2649, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2303, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2309, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

I tried also to use the switch --no-deps but i get the same message.

**Comment by vrs01** [comment]
Google is your friend :-)
https://stackoverflow.com/questions/27341064/how-do-i-fix-importerror-cannot-import-name-incompleteread

**Comment by ansraliant** [comment]
I had a similar issue on Ubuntu. Try upgrading pip and then trying again. 

The package python-pip has an old version of pip.

_Sent from my Sony F8332 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jaedb** [comment]
@tulipo Please close this issue if following the above steps fixes the problem.

**Comment by tulipo** [comment]
Solved.... Thanks a lot for help... I apoligize for my lazyness to not googling..........
