### ISSUE TITLE
Updating / uninstalling via pip on Raspbian

### ISSUE THREAD

**Issue by Cyberek** [jaedb/Iris#197]
## Expected behavior
upgrade or uninstall of Mopidy-Iris should finish correctly
## Actual behavior
```
sudo pip install --upgrade Mopidy-Iris
sudo pip install --upgrade --no-deps Mopidy-Iris
sudo pip uninstall Mopidy-Iris
```
all returns:
```
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
```

## Steps to replicate
1.  run "sudo pip install --upgrade Mopidy-Iris" on Raspbian (current version, updated) after installing Mopidy-Iris before (older version, 3.3.1).
2.

#### Operating systems affected
- [X] Other: Raspbian

## Before you submit
- [X] Yes, I have tested this issue thoroughly
- [X] Yes, I have attached screenshots and/or screencast of the issue in action
- [X] Yes, I have included any relevant debug data and error logs

**Comment by Cyberek** [comment]
Ok, it looks like a pip issue itself, this have solved it:
`sudo easy_install -U pip`
