### ISSUE TITLE
Spotipy missing as dependency?

### ISSUE THREAD

**Issue by Hakonvl** [jaedb/Iris#204]
Installed mopidy from their on repo onto a freshly installed Rasbpian-installation. Installed mopidy-spotify via apt-get, and iris via pip. 

Irirs did not show up via the mopidy web server.  Checked /etc/mopidy/mopidy.log, and found this:

`017-09-13 22:06:01,218 INFO [1185:MainThread] mopidy.__main__: Starting Mopidy 2.1.0
2017-09-13 22:06:01,453 ERROR [1185:MainThread] mopidy.ext: Failed to load extension iris: No module named spotipy
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/ext.py", line 202, in load_extensions
    extension_class = entry_point.load(require=False)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/__init__.py", line 7, in <module>
    import handlers
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/handlers.py", line 5, in <module>
    from spotipy import Spotify
ImportError: No module named spotipy
`

Installed spotipy from pip, and iris did show up as it is should. 

Is spotipy missing as a dependency in the iris pip-package?

**Comment by jaedb** [comment]
Firstly, please use the provided issue template. There is a reason this is in place.

Secondly, a [quick search](https://github.com/jaedb/Iris/issues?utf8=%E2%9C%93&q=dependency) will reveal this issue has already been discussed and is pending release.
