### ISSUE TITLE
Failed to load extension iris: No module named html.entities

### ISSUE THREAD

**Issue by emanuel7L** [jaedb/Iris#346]
## Expected behavior
-/-

## Actual behavior
ERROR    Failed to load extension iris: No module named html.entities
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mopidy/ext.py", line 202, in load_extensions
    extension_class = entry_point.load(require=False)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/__init__.py", line 12, in <module>
    from core import IrisCore
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/core.py", line 4, in <module>
    import random, string, logging, json, pykka, pylast, urllib, urllib2, os, sys, mopidy_iris, subprocess
  File "/usr/local/lib/python2.7/dist-packages/pylast/__init__.py", line 33, in <module>
    import html.entities
ImportError: No module named html.entities

## Steps to replicate
1. Run **mopidy** in the command line

#### Operating systems affected
- [ ] Linux: Ubuntu 16.04

#### Browsers affected
-/-

#### Screen sizes affected
-/-

## Additional details, debug data, logs, etc
This started to happen since version 3.31.8
Already tried reinstall both mopidy and Iris with no luck

**Comment by emanuel7L** [comment]
Just tried changing html.entities to htmlentities within /usr/local/lib/python2.7/dist-packages/pylast/__init__.py but now it says **_ImportError: No module named http.client_**

**Comment by emanuel7L** [comment]
Solved by manually installing pylast v1.6.0, for some reason upgraind mopidy-iris itself was installing pylast 3.0.0

**Comment by mpk1001** [comment]
Same issue. Upgrading to 3.31.8 stopped Iris working until pylast v1.6.0 is installed.

`pip install pylast==1.6.0`

**Comment by jaedb** [comment]
@emanuel7L and @mpk1001 can you confirm that the latest version resolves this issue for you?

**Comment by emanuel7L** [comment]
@jaedb 3.32.0 seems to fix the issue, thanks!
