### ISSUE TITLE
Uncaught exeption when server not connected to the internet

### ISSUE THREAD

**Issue by blockmurder** [jaedb/Iris#410]
**Describe the bug**
Using Iris on a server with no internet connection (living on a sailing boat, server is not allways connected to the internet), Iris produces loads of uncaught exceptions. The Iris interface is therefore rendered unusable as it is not responding anymore.
 
**To Reproduce**
1. Disconnect the server form the internet
2. Restart mopidy, make sure iris extension is loaded
3. Open iris web interface
4. Setting username allready fails

**Expected behavior**
Iris web interface should fail to load any content from the internet (e.g. cover art) but otherwise function normally.

**Screenshots**
No screenshot, but the log from mopidy:
```
INFO     Starting Mopidy 2.2.2
INFO     Loading config from builtin defaults
INFO     Loading config from /home/pulse/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: iris, mpd, http, stream, local-sqlite, softwaremixer, file, local-images, local, m3u
INFO     Disabled extensions: none
INFO     Starting Mopidy mixer: SoftwareMixer
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, LocalBackend
INFO     Audio output set to "autoaudiosink"
INFO     Loaded 2192 local tracks using sqlite
INFO     Starting Mopidy core
INFO     Starting Mopidy frontends: IrisFrontend, MpdFrontend, HttpFrontend
INFO     Starting Iris 3.33.0
INFO     MPD server running at [::ffff:0.0.0.0]:6600
INFO     HTTP server running at [::ffff:0.0.0.0]:8080
INFO     Starting GLib mainloop
ERROR    Uncaught exception in /iris/ws/
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/websocket.py", line 494, in _run_callback
    result = callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/handlers.py", line 92, in on_message
    getattr(mem.iris, message['method'])(data=params, callback=lambda response, error=False: self.handle_result(id=id, method=message['method'], response=response, error=error))
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/core.py", line 432, in get_version
    response = urllib2.urlopen(req, timeout=30).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
ERROR    Uncaught exception in /iris/ws/
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/websocket.py", line 494, in _run_callback
    result = callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/handlers.py", line 92, in on_message
    getattr(mem.iris, message['method'])(data=params, callback=lambda response, error=False: self.handle_result(id=id, method=message['method'], response=response, error=error))
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/core.py", line 432, in get_version
    response = urllib2.urlopen(req, timeout=30).read()
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
```

**Environment details:**
 - OS: Docker container (Ubuntu 17.10)
 - Browser: Chromium 75
 - Iris version: 3.33.0

**Additional context**
Issue seems to be fixed by changing L409 in core.py from
```except urllib2.HTTPError as e:```
to
```except (urllib2.HTTPError, urllib2.URLError) as e:```

**Comment by jaedb** [comment]
Thanks for the thorough bug report, and the suggested fix. Feel free to make a pull request for any future fixes, but for this one I've applied your suggested fix (see commit 13a54de40286c496ef359de9d05c8843b1a76d4f).
