### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by fmarzocca** [jaedb/Iris#452]
**Describe the bug**
I have hundreds of this lines in the log:

```
2019-10-21 18:16:03,825 INFO [19640:HttpServer] tornado.access: 200 GET /iris/ws/ (10.0.0.229) 5.52ms
2019-10-21 18:16:12,179 ERROR [19640:HttpServer] tornado.application: Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/lib/python2.7/dist-packages/tornado/websocket.py", line 721, in _accept_connection
    self.selected_subprotocol = self.handler.select_subprotocol(subprotocols)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/handlers.py", line 28, in select_subprotocol
    return subprotocols[0]
IndexError: list index out of range
2019-10-21 18:16:12,182 INFO [19640:HttpServer] tornado.access: 200 GET /iris/ws/ (10.0.0.229) 5.95ms
```
**Expected behavior**
I have restarted mopidy service, but the errors are still there, growing very fast.

**Environment details:**
 - OS: RaspBian
 - Browser: N/A
 - Iris version: 3.41.1

**Comment by jaedb** [comment]
What version of Mopidy are you running? Try upgrading both Mopidy and Iris to see if the issue persists. I believe this particular error was resolved in the most recent release of Iris.

**Comment by fmarzocca** [comment]
Mopidy is 2.3.1.
Just updated Iris to 3.41.2 and it looks like fixed. No more error messages.
