### ISSUE TITLE
Broken album view

### ISSUE THREAD

**Issue by jjok** [jaedb/Iris#495]
**Describe the bug**
When I go to the "album" view, it starts to load, but then the screen just goes blank. It worked before, when I was running the Python 2 versions of everything, but this hasn't worked since I upgraded to Python 3.

**To Reproduce**
1. Click on "Albums" under "My Music".
2. The page starts to load.
3. The page goes black.
4. See error below.

**Expected behavior**
Albums should be listed.

**Screenshots**
I get this in the browser console.

```
TypeError: "o.toLowerCase is not a function"
    o http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:1
    sortItems http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:1
    value http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:125
    value http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:125
    Po http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:81
    Co http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:81
    Mo http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:81
    Gi http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:81
    Wi http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:81
    Ps http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:81
    As http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:81
    ks http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:81
    Qi http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:81
    enqueueSetState http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:81
    setState http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:73
    unsubscribe http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:1
    y http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:1
    f http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:112
    c http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:112
    i http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:112
    i http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:112
    d http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:112
    m http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:98
    v http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:98
    u http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:98
    f http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:98
    a http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:112
    r http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:98
    dispatch http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:1
    getLibraryAlbumsProcessor http://kitchen-musicbox.local:6680/iris/app.min.js?v=1580372023:1
app.min.js:81:74995
TypeError: o.toLowerCase is not a function app.min.js:1:19024
```

**Environment details:**
 - OS: Raspbian / Raspberry Pi 2 / Docker (https://github.com/jjok/my-mopidy-setup)
 - Browser: Firefox - Ubuntu
 - Iris: 3.44.0

**Additional context**
I don't think I'm getting any errors in the Mopidy log. There are some Iris-related errors, but I'm not sure they're related to this issue.

```
ERROR    2020-02-10 18:47:59,006 [1:IrisFrontend-14] mopidy.listener
  Triggering event failed: tracklist_changed()
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/listener.py", line 40, in on_event
    getattr(self, event)(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_iris/frontend.py", line 28, in tracklist_changed
    iris.ioloop.add_callback( functools.partial(iris.clean_queue_metadata) )
AttributeError: 'NoneType' object has no attribute 'add_callback'
ERROR    2020-02-10 20:45:54,252 [1:IrisFrontend-14] mopidy.listener
  Triggering event failed: tracklist_changed()
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/listener.py", line 40, in on_event
    getattr(self, event)(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_iris/frontend.py", line 28, in tracklist_changed
    iris.ioloop.add_callback( functools.partial(iris.clean_queue_metadata) )
AttributeError: 'NoneType' object has no attribute 'add_callback'
ERROR    2020-02-10 20:45:54,257 [1:IrisFrontend-14] mopidy.listener
  Triggering event failed: track_playback_ended(tl_track, time_position)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/listener.py", line 40, in on_event
    getattr(self, event)(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_iris/frontend.py", line 25, in track_playback_ended
    iris.ioloop.add_callback( functools.partial(iris.check_for_radio_update) )
AttributeError: 'NoneType' object has no attribute 'add_callback'
```

**Comment by jjok** [comment]
Those Python errors are almost certainly unrelated. They happened a couple of hours ago, whereas I've been reproducing this issue in the last few minutes.

**Comment by jjok** [comment]
The album view is filtered to just show albums from Spotify. I don't think I can test it with other backends, as the page breaks before I can click the filter.

**Comment by jaedb** [comment]
Can you please try _Settings > Clear cache_ and also hard refresh (usually `shift + F5`) your browser? Next step is to enable _Settings > Debug > Test mode_ and provide the browser console output. This will give you more verbose error output to make it easier to debug.

**Comment by jjok** [comment]
Hmm. I've done a hard refresh and that doesn't seem to help.

I tried doing "Reset cache" in Iris and I get a "Service Worker not supported" error. Seems weird. I'm on Firefox 72 on Linux. I would've thought service workers should work.

https://caniuse.com/#search=service%20worker

**Comment by jjok** [comment]
I enabled Debug mode.

This is from clicking on Reset Cache.
```
Service Worker not supported null 
{…}
​
description: null
​
message: "Service Worker not supported"
​
state: Object { core: {…}, ui: {…}, spotify: {…}, … }
​
<prototype>: Object { … }
middleware.js:84:16
XHRGEThttps://api.spotify.com/v1/me/albums?limit=50
[HTTP/2 200 OK 2014ms]
```

This is what happens when I click on Albums.

```
The above error occurred in the <LibraryAlbums> component:
    in LibraryAlbums (created by Context.Consumer)
    in Connect(LibraryAlbums) (created by Route)
    in Route (created by App)
    in Switch (created by App)
    in main (created by App)
    in div (created by App)
    in Route (created by App)
    in Switch (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by Context.Consumer)
    in Connect(App) (created by Route)
    in Route
    in Router (created by BrowserRouter)
    in BrowserRouter
    in Provider

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. react-dom.development.js:17117
TypeError: a_value.toLowerCase is not a function helpers.js:1398:18
    compare helpers.js:1398
    comparefn self-hosted:220
    InsertionSort self-hosted:3570
    MergeSort self-hosted:3635
    sort self-hosted:223
    sortItems helpers.js:1404
    renderView LibraryAlbums.js:192
    render LibraryAlbums.js:343
    React 17
    Redux 2
    SnapcastMiddleware middleware.js:637
    GoogleMiddleware middleware.js:135
    GeniusMiddleware middleware.js:53
    LastfmMiddleware middleware.js:32
    SpotifyMiddleware middleware.js:331
    PusherMiddleware middleware.js:789
    MopidyMiddleware middleware.js:2410
    UIMiddleware middleware.js:240
    CoreMiddleware middleware.js:798
    localstorageMiddleware middleware.js:11
    Redux 2
    getLibraryAlbumsProcessor actions.js:1940
TypeError: a_value.toLowerCase is not a function helpers.js:1398:18
```

**Comment by jaedb** [comment]
Thanks heaps for that extra info. The ultimate issue appears to be with the sorting of your Library Albums because something is giving the sorting code a non-value (`a_value.toLowerCase is not a function`).
If you reset your client settings (_Settings > Reset all settings_) does that fix the issue? It is possible that you've got an outdated or deprecated sort configuration, and a reset would confirm whether that is the case.

**Comment by jjok** [comment]
That sounds plausible. Maybe related to #397?

**Comment by jjok** [comment]
> If you reset your client settings (Settings > Reset all settings) does that fix the issue?
Yep. That fixed it.

I'm seeing various other JavaScript errors in the console, but I haven't worked out how to reproduce any of them, so I'll close this one. Thanks.

**Comment by jjok** [comment]
@jaedb Should there be a message somewhere says "If you're upgrading from version x to y then you need to do a reset" or something?
