### ISSUE TITLE
Radio stops playing

### ISSUE THREAD

**Issue by beaufour** [jaedb/Iris#554]
**Describe the bug**

I recently upgraded from .40 (a bit behind :) ), to .49 1589790097, and now the radio function stops playing at some point. I usually have it playing constantly, and it never stopped previously.

**To Reproduce**
1. Open the app
2. Click radio
3. Add a few artists
4. Click save

Result: after X amount of time (hours?) the radio stops playing.

**Expected behavior**
Radio should never stop.

**Environment details:**
 - OS: Mac OS 
 - Browser Chrome
 - Iris version 3.49.0

**Additional context**
There are not errors in the console, and the playlist/queue is empty. If I click Radio, the artists are still there, and if I click Save the queue is filled and the radio starts playing again.

**Comment by eskech** [comment]
Observation.
If radio is playing and a user add music to the queue, the radio do not take over when the queue is empty. In the older version it added new tracks if there where less than 3 tracks in queue.

**Comment by fmarzocca** [comment]
My radio stops very frequently and this is very annoying. I can't afford any station for long playing (TuneIn, RadioTunes, etc.).

It stops with this error in the log:

```
Jun 30 09:35:32 pab mopidy[520]: ERROR    [MainThread] mopidy.audio.gst GStreamer error: Server does
 not support seeking.
```

**Comment by jaedb** [comment]
@eskech and @beaufour do either of you observe any errors in the Mopidy output similar to @fmarzocca?

**Comment by beaufour** [comment]
> @eskech and @beaufour do either of you observe any errors in the Mopidy output similar to @fmarzocca?

No, but I am seeing a fair bunch of these:

```
mopidy_1   | ERROR    2020-06-17 20:20:20,993 [6:HttpServer] tornado.application
mopidy_1   |   Exception in callback functools.partial(<bound method IrisCore.check_for_radio_update of <mopidy_iris.core.IrisCore object at 0x7fbe50918a50>>)
mopidy_1   | Traceback (most recent call last):
mopidy_1   |   File "/usr/local/lib/python3.7/site-packages/tornado-6.0.4-py3.7-linux-x86_64.egg/tornado/ioloop.py", line 743, in _run_callback
mopidy_1   |     ret = callback()
mopidy_1   |   File "/iris/mopidy_iris/core.py", line 730, in check_for_radio_update
mopidy_1   |     self.radio["results"] = uris[3:]
mopidy_1   | TypeError: 'coroutine' object is not subscriptable
```

**Comment by jaedb** [comment]
That would definitely cause the radio to stop working. Basically `check_for_radio_update` is responsible for checking whether we need to load more tracks from Spotify, and if so, actually loading them. So I think this is our culprit (or at least a place to start looking).

This is the juggle of `async/await` in Python that I haven't quite cracked.

**Comment by beaufour** [comment]
> That would definitely cause the radio to stop working. Basically `check_for_radio_update` is responsible for checking whether we need to load more tracks from Spotify, and if so, actually loading them. So I think this is our culprit (or at least a place to start looking).
> 
> This is the juggle of `async/await` in Python that I haven't quite cracked.

Let me know if we can help debug.

**Comment by djmattyg007** [comment]
Is someone able to provide a concrete set of steps to replicate this issue? I think I've got a fix, but I'd like to be able to test it before I submit a PR for it.

**Comment by beaufour** [comment]
> Is someone able to provide a concrete set of steps to replicate this issue? I think I've got a fix, but I'd like to be able to test it before I submit a PR for it.

I don't have much more than "just keep the radio playing for long enough" (hours). But it happens fairly consistently for me, so I can apply your patch locally and see if it fixes it

**Comment by fmarzocca** [comment]
Same here

Il giorno ven 17 lug 2020 alle 15:15 Allan Beaufour <
notifications@github.com> ha scritto:

**Comment by djmattyg007** [comment]
https://gist.github.com/djmattyg007/39709d1c05a750f5167a19b8889dcc55

The changes to `core.py` are for the issue described here. The changes to `frontend.py` are for the issue I described on #560.

**Comment by kingosticks** [comment]
I don't follow those changed to IrisCore. Would you mind explaining them?

**Comment by djmattyg007** [comment]
If it looks good I'll submit as a PR tomorrow.

**Comment by djmattyg007** [comment]
Life kinda got in the way of this :( but it does appear as though the change I was going to make has now been made as part of #595

So if the problem is still occurring, some further investigation is going to be required.

**Comment by beaufour** [comment]
Life happens :) I upgraded to the latest version recently but also threw in some debug statements. I haven't seen the error since. But whether it was fixed by the debug statements or the latest code I cannot say, although I would bet on the latter.

**Comment by jaedb** [comment]
Closing due to inactivity. Please feel free to re-open if the issue persists.
