### ISSUE TITLE
Support for mopidy-ytmusic?

### ISSUE THREAD

**Issue by DIYglenn** [jaedb/Iris#716]
The [mopidy-ytmusic](https://github.com/OzymandiasTheGreat/mopidy-ytmusic) plug-in seems to be the best way of getting YouTube Music working with Mopidy. 

YouTube Music (Premium) works, but is a bit clumsy under Iris, as you have to “Browse” menus. It also seems like “Artist” etc doesn’t work, but that could be a current limitation of the plug-in.  

Is there any chance that Iris could get integrated YT Music support? I like Spotify, but the YouTube Premium family subscription is something we appreciate as there are no ads in videos etc. 

![B8FF90A2-6BB4-45A0-83BA-AB5A94C95A7E](https://user-images.githubusercontent.com/10504432/111673409-3c2cde00-881b-11eb-82a3-5e90249d6456.jpeg)

**Comment by rebernet** [comment]
I would also be very interested in this feature.

**Comment by jaedb** [comment]
Further investigation will be needed. I have found that to achieve a rich experience (like that of Spotify), the provider should have a HTTP API that Iris can communicate directly with.

This may be possible with [Youtube API v3](https://developers.google.com/youtube/v3).

**Comment by kingosticks** [comment]
Please be take note of the API terms, [we had problems before](https://github.com/natumbri/mopidy-youtube/issues/92).

**Comment by DIYglenn** [comment]
> Please be take note of the API terms, [we had problems before](https://github.com/natumbri/mopidy-youtube/issues/92).

But is that related to Music though, or only YouTube “Video”?

**Comment by kingosticks** [comment]
That is related to using the Youtube API v3, there previously was no distinction between music and video. I don't know what Music-specific APIs now exist. What I am saying is whatever YouTube API you end up using, just be careful to comply with the ToS as they do enforce them and losing access to your personal Google account can be particularly awkward.

**Comment by jaedb** [comment]
Mopidy-YTMusic is actually a relatively capable backend (despite needing a hands-on authentication) so it may not require a HTTP integration. I think my preferred way to handle this is to allow users to set the URIs used to populate _My Music_ sections (not just the _Browse_ section).

**Comment by rebernet** [comment]
I can confirm, the Mopidy-YTMusic backend works quite well.  But only with _Search_ and clicking on the Artist in the collected result. When selecting an album it appears empty (with no tracks).

**Comment by zxpetrel** [comment]
> 
> 
> I can confirm, the Mopidy-YTMusic backend works quite well. But only with _Search_ and clicking on the Artist in the collected result. When selecting an album it appears empty (with no tracks).

The ytmusic backend works quite nicely with Muse but when I use Iris I find the opposite - Album works better than Artist.  For Artist I initially see a list of tracks but then the whole plugin becomes inaccesible except for one track (back does not work).  For Albums I see everything I saved in my Youtube Music account.  The problem I have with albums is the track order in Iris is alphabetical, not usually what I want.

**Comment by keesfluitman** [comment]
Hello, Thank you for this lovely repository. 
Ive noticed that ytmusic is active in this package, but when I use "docker exec iris mopidy ytmusic setup" It wont start the auth.json activation process, but rather give me the following error:

`INFO     2022-03-10 09:32:37,529 [138:MainThread] mopidy.__main__
  Starting Mopidy 3.2.0
INFO     2022-03-10 09:32:37,561 [138:MainThread] mopidy.config
  Loading config from builtin defaults
INFO     2022-03-10 09:32:37,564 [138:MainThread] mopidy.config
  Loading config from file:///config/mopidy.conf
INFO     2022-03-10 09:32:37,564 [138:MainThread] mopidy.config
  Loading config from command line options
INFO     2022-03-10 09:32:37,898 [138:MainThread] mopidy.__main__
  Enabled extensions: http, musicbox_webclient, m3u, file, stream, softwaremixer, tunein, dleyna, podcast, spotify, iris, mpd, ytmusic, youtube
INFO     2022-03-10 09:32:37,898 [138:MainThread] mopidy.__main__
  Disabled extensions: tidal, local, soundcloud, jellyfin
WARNING  2022-03-10 09:32:37,899 [138:MainThread] mopidy.__main__
  Found local configuration errors. The extension has been automatically disabled:
WARNING  2022-03-10 09:32:37,899 [138:MainThread] mopidy.__main__
    local/media_dir must be set.
WARNING  2022-03-10 09:32:37,899 [138:MainThread] mopidy.__main__
  Please fix the extension configuration errors or disable the extensions to silence these messages.
Enter the path where you want to save auth.json [default=current dir]: ERROR    2022-03-10 09:32:38,291 [138:MainThread] mopidy.__main__
  EOF when reading a line
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/Mopidy-3.2.0-py3.7.egg/mopidy/__main__.py", line 143, in main
    return args.command.run(args, proxied_config)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_ytmusic/command.py", line 23, in run
    "Enter the path where you want to save auth.json [default=current dir]: "
EOFError: EOF when reading a line
Traceback (most recent call last):
  File "/usr/local/bin/mopidy", line 11, in <module>
    load_entry_point('Mopidy', 'console_scripts', 'mopidy')()
  File "/usr/local/lib/python3.7/dist-packages/Mopidy-3.2.0-py3.7.egg/mopidy/__main__.py", line 143, in main
    return args.command.run(args, proxied_config)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_ytmusic/command.py", line 23, in run
    "Enter the path where you want to save auth.json [default=current dir]: "
EOFError: EOF when reading a line
`

I'd love to add my ytmusic library and playlists. Anything Im missing perhaps?
If I can get this all working properly, so I have my spotify library, ytmusic library and mixcloud and soundcloud working, I'm a very happy man and will gladly give some money.

It's just that I get this error, can't get soundcloud, mixcloud and bandcamp to work either.

**Comment by jaedb** [comment]
Because this is prompting for user input, you will need to execute the command with an [interactive terminal](https://docs.docker.com/engine/reference/commandline/exec/#options).

The short version: try `docker exec -it iris mopidy ytmusic setup`

**Comment by keesfluitman** [comment]
Thanks. Something I didn't know yet.
Is it true though, that even though I've properly authenticated it now, it still doesn't integrate my youtube music playlists within the "playlist" sector with local and spotify? Because the only way I can find them, is by simply searching their names in the search function.

Thanks anyway. It's already a great way to play around, even if it's use is slowly dieing.

**Comment by shadowking001** [comment]
Since Spotify is not part of the game anymore, YT-music could be nice to inspect furthermore #841

**Comment by jaedb** [comment]
Mopidy-YT music support has been taken as far as it can go, unless there is something specific that is not working as you see fit? I am rather limited here as there is no YT Music HTTP API for Iris to supplement the interface it with (like there is for Spotify).
