### ISSUE TITLE
ImportError: cannot import name Spotify

### ISSUE THREAD

**Issue by rlukasz** [jaedb/Iris#78]
Hi, after installation Iris I got this error while mopidy starts:

```
2017-03-04 14:14:15,060 ERROR [1652:MainThread] mopidy.ext: Failed to load extension iris: cannot import name Spotify
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/ext.py", line 202, in load_extensions
    extension_class = entry_point.load(require=False)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2281, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2287, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/__init__.py", line 7, in <module>
    import handlers
  File "/usr/local/lib/python2.7/dist-packages/mopidy_iris/handlers.py", line 9, in <module>
    from spotipy import Spotify
ImportError: cannot import name Spotify
```

Earlier I was using older version of spotmop and it worked ok. Error came after I switch to current version of Iris.

I'm using Cubian (based on Debian jessie 8.7) on Cubieboard2. Mopidy version 2.1.0.
Currently I fix this by modify frontend.py

`+ import spotipy`

I'm not sure if this is common issue.

**Comment by jaedb** [comment]
Have you installed Iris using `pip install --upgrade Mopidy-Iris`? It sounds like the Spotipy module is not loading properly, which wouldn't be installed if Iris' dependencies haven't been installed.

**Comment by rlukasz** [comment]
`pip install --upgrade Mopidy-Iris ` solved the problem. Thanks
