### ISSUE TITLE
My Playslist window get a spinner

### ISSUE THREAD

**Issue by dnj0104** [jaedb/Iris#816]
### Iris version

3.55.4

### Operating system(s) affected

- [X] Windows
- [ ] MacOS
- [ ] iOS
- [X] Android
- [X] Linux
- [ ] Other

### Browser(s) affected

- [X] Firefox
- [ ] Chrome
- [ ] Edge
- [X] Other

### What happened?

opens up iris in web browser this case Brave, but same problem with firefox and chromium, anyway, I open browser and press My playlist, and first sometimes it says 1/79 and then changes to 1/2 and the spinner start to spinns and nothing happens.

I can search through my local library, and find spotify song thru search field, Artist,Song and everything else works.

I had tried the debug mode, but no luck or results from there, BUT when in debug mode in Mopidy-field I got a list with all my
Spotify and local playlitst .

I had also tried to re-authorize Iris and got a new spotify client-id and client- secret, and start and stop services 

### Logs

```shell
some errors from journalctl -u mopidy

Mar 06 16:28:13 MopidyNest mopidy[623]: ERROR    [Core-11] mopidy.core.library SpotifyBackend backend caused an exception.
Mar 06 16:28:13 MopidyNest mopidy[623]: Traceback (most recent call last):
Mar 06 16:28:13 MopidyNest mopidy[623]:   File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
Mar 06 16:28:13 MopidyNest mopidy[623]:     yield
Mar 06 16:28:13 MopidyNest mopidy[623]:   File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 181, in get_images
Mar 06 16:28:13 MopidyNest mopidy[623]:     if future.get() is None:
Mar 06 16:28:13 MopidyNest mopidy[623]:   File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
Mar 06 16:28:13 MopidyNest mopidy[623]:     _compat.reraise(*self._data['exc_info'])
Mar 06 16:28:13 MopidyNest mopidy[623]:   File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
Mar 06 16:28:13 MopidyNest mopidy[623]:     raise value
Mar 06 16:28:13 MopidyNest mopidy[623]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
Mar 06 16:28:13 MopidyNest mopidy[623]:     response = self._handle_receive(envelope.message)
Mar 06 16:28:13 MopidyNest mopidy[623]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
Mar 06 16:28:13 MopidyNest mopidy[623]:     return callee(*message.args, **message.kwargs)
Mar 06 16:28:13 MopidyNest mopidy[623]:   File "/usr/lib/python3/dist-packages/mopidy_spotify/library.py", line 35, in get_images
Mar 06 16:28:13 MopidyNest mopidy[623]:     return images.get_images(self._backend._web_client, uris)
Mar 06 16:28:13 MopidyNest mopidy[623]:   File "/usr/lib/python3/dist-packages/mopidy_spotify/images.py", line 23, in get_images
Mar 06 16:28:13 MopidyNest mopidy[623]:     uris = sorted((_parse_uri(u) for u in uris), key=uri_type_getter)
Mar 06 16:28:13 MopidyNest mopidy[623]:   File "/usr/lib/python3/dist-packages/mopidy_spotify/images.py", line 23, in <genexpr>
Mar 06 16:28:13 MopidyNest mopidy[623]:     uris = sorted((_parse_uri(u) for u in uris), key=uri_type_getter)
Mar 06 16:28:13 MopidyNest mopidy[623]:   File "/usr/lib/python3/dist-packages/mopidy_spotify/images.py", line 45, in _parse_uri
Mar 06 16:28:13 MopidyNest mopidy[623]:     uri_type, uri_id = parsed_uri.path.split(":")[:2]
Mar 06 16:28:13 MopidyNest mopidy[623]: ValueError: not enough values to unpack (expected 2, got 1)
Mar 06 16:28:36 MopidyNest mopidy[623]: ERROR    [M3UBackend-5] mopidy.m3u.playlists Error reading playlist 'm3u:%5BRadio%20Streams%5D.m3u8': Permission denied
```

**Comment by dnj0104** [comment]
Solved I removed the m3u playlist in my above log 

`ar 06 16:28:36 MopidyNest mopidy[623]: ERROR    [M3UBackend-5] mopidy.m3u.playlists Error reading playlist 'm3u:%5BRadio%20Streams%5D.m3u8': Permission denied`

and now my Iris found my playlists again
